// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqoJIidWcQhi6Jf4BJLNu3IGwFC4--ba0',
    appId: '1:252734026318:web:1a959d2484d88099c6891f',
    messagingSenderId: '252734026318',
    projectId: 'ujitsugym',
    authDomain: 'ujitsugym.firebaseapp.com',
    storageBucket: 'ujitsugym.firebasestorage.app',
    measurementId: 'G-FH3BHXPEWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqppNGHJs2NdRbzEO_SQ4-2ktW_-Bbevo',
    appId: '1:252734026318:android:62b4bcc64bfca140c6891f',
    messagingSenderId: '252734026318',
    projectId: 'ujitsugym',
    storageBucket: 'ujitsugym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu24DPuF4oMHnyCQdrGgF04BDF9UlZO8U',
    appId: '1:252734026318:ios:f86fb9ed0a172cbac6891f',
    messagingSenderId: '252734026318',
    projectId: 'ujitsugym',
    storageBucket: 'ujitsugym.firebasestorage.app',
    iosBundleId: 'com.ujitsugym.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu24DPuF4oMHnyCQdrGgF04BDF9UlZO8U',
    appId: '1:252734026318:ios:c7a95392bfd6787dc6891f',
    messagingSenderId: '252734026318',
    projectId: 'ujitsugym',
    storageBucket: 'ujitsugym.firebasestorage.app',
    iosBundleId: 'com.example.calebshirthum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqoJIidWcQhi6Jf4BJLNu3IGwFC4--ba0',
    appId: '1:252734026318:web:414bf73afb615fa5c6891f',
    messagingSenderId: '252734026318',
    projectId: 'ujitsugym',
    authDomain: 'ujitsugym.firebaseapp.com',
    storageBucket: 'ujitsugym.firebasestorage.app',
    measurementId: 'G-JYF5RTE714',
  );
}
